version: "2"
services:
  facebook_bot:
    build: "./facebook-bot/"
    working_dir: /facebook-bot/app
    environment:
      - VERIFY_TOKEN=
      - ACCESS_TOKEN=
      - APP_SECRET=
    ports:
      - "127.0.0.1:5000:5000"
    command: "gunicorn -w 4 --log-level info --bind 0.0.0.0:5000 bot:app"
    volumes:
      - ./submitted:/submitted
  tensorflow_serving:
    build: "./inference/"
    working_dir: /fb-model
    environment:
      - ENV BAZEL_VERSION 0.5.4
      - BAZELRC /root/.bazelrc
    expose:
      - "9000"
volumes:
  submitted: